#!/bin/bash

MONITORS=$(xrandr --query | grep " connected" | cut -d" " -f1)

export GTK_THEME=Arc-Dark 
export GTK_ICON_THEME=Papirus-Dark 
export XCURSOR_THEME=Brezze
export XCURSOR_SIZE=24

pulseaudio --start &
sxhkd &
picom &
konsole &
feh --bg-scale ~/bg/bg_01.jpg &
~/.config/polybar/launch.sh &
bspc monitor HDMI-A-0 -d 1 2 3 &
bspc monitor DVI-D-0 -d 1 2 3 &

bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#81a1c1"
bspc config presel_feedback_color "#2e3440"

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

xset -dpms
xset s off
xset s noblank
