#!/bin/bash

MONITORS=$(xrandr --query | grep " connected" | cut -d" " -f1)
export GTK_THEME="/usr/share/themes/Art"
export GTK_ICON_THEME="/usr/share/icons/Fluent-orange"
gsettings set org.gnome.desktop.interface gtk-theme "Art" &
gsettings set org.gnome.desktop.interface gtk-icon-theme "Fluent-orange" &

pulseaudio --start &
sxhkd -c ~/.config/bspwm/themes/Art/sxhkd/sxhkdrc &
picom --config ~/.config/bspwm/themes/Art/picom/config.conf &
#picom &
kitty &
feh --no-fehbg --bg-fill "$(find ~/bg -type f | shuf -n 1)" &
~/.config/bspwm/themes/Art/polybar/launch.sh &
bspc monitor -d 1 2 3 4 5 &

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

xset -dpms
xset s off
xset s noblank
